apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-app
  namespace: crm
  labels:
    app: crm-app
    release: crm-app
spec:
  selector:
    matchLabels:
      app: crm-app
      release: crm-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: crm-app
        release: crm-app
        tier: frontend
    spec:
      imagePullSecrets:
      - name: dockerconfig
      containers:
      - image: registry.gitlab.com/steffbeckers/crm/app
        name: crm-app
        ports:
        - containerPort: 80
          name: crm-app
---
apiVersion: v1
kind: Service
metadata:
  name: crm-app
  namespace: crm
  labels:
    app: crm-app
    release: crm-app
spec:
  ports:
    - port: 80
  selector:
    app: crm-app
    release: crm-app
    tier: frontend
