apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-api
  namespace: crm
  labels:
    app: crm-api
    release: crm-api
spec:
  selector:
    matchLabels:
      app: crm-api
      release: crm-api
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: crm-api
        release: crm-api
        tier: backend
    spec:
      imagePullSecrets:
      - name: dockerconfig
      containers:
      - image: registry.gitlab.com/steffbeckers/crm/api
        name: crm-api
        ports:
        - containerPort: 80
          name: crm-api
---
apiVersion: v1
kind: Service
metadata:
  name: crm-api
  namespace: crm
  labels:
    app: crm-api
    release: crm-api
spec:
  ports:
    - port: 80
  selector:
    app: crm-api
    release: crm-api
    tier: backend
