version: "3.7"

services:
  app:
    image: registry.gitlab.com/steffbeckers/crm/app
    networks:
      - reverse-proxy_default
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - mssql
      - api
  api:
    image: registry.gitlab.com/steffbeckers/crm/api
    networks:
      - reverse-proxy_default
      - default
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    networks:
      - default
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=epujl3bcn4t9dp12fdtaz6bwnl3emohyxyue936p5ls1zoeangtpw4bb9v9hmpu3
    volumes:
      - /root/crm_dev/mssql:/var/opt/mssql

networks:
  reverse-proxy_default:
    external: true
  default:
    internal: true
